# 🐼 Pandas — Complete Beginner's Guide

> **Pandas** = **Pan**el **Da**ta (from econometrics)  
> It is the most popular Python library for **data analysis and manipulation**.  
> If NumPy is for numbers, Pandas is for **tables** (like Excel/Google Sheets but in Python).

| Task | Without Pandas | With Pandas |
|------|---------------|-------------|
| Read a CSV file | `open()`, loops, split | `pd.read_csv('file.csv')` |
| Filter rows | Manual loops | `df[df['marks'] > 90]` |
| Group by category | Dict + loops | `df.groupby('class').mean()` |
| Handle missing data | if-else checks | `df.fillna(0)` |

---

## 1. Installation & Import

In [1]:
# Install pandas (uncomment if needed)
# !pip install pandas

In [2]:
import pandas as pd    # 'pd' is the universal shorthand
import numpy as np     # Often used together with NumPy

print(f"Pandas version: {pd.__version__}")

Pandas version: 2.2.2

---

## 2. Series — 1-D Data

A **Series** is like a single column of data with labels (index).

> 🧠 **Think of Series as:** A numbered (or labeled) list — like one column from an Excel sheet.

In [3]:
# From a list (auto-numbered index)
marks = pd.Series([85, 90, 78, 92, 88])
print("Series from list:")
print(marks)

Series from list:
0    85
1    90
2    78
3    92
4    88
dtype: int64

In [4]:
# With custom labels (index)
marks = pd.Series(
    [85, 90, 78, 92, 88],
    index=['Alice', 'Bob', 'Charlie', 'David', 'Eve']
)
print("Series with custom index:")
print(marks)
print()

# Access by label
print(f"Bob's marks: {marks['Bob']}")
print(f"Alice & Eve: \n{marks[['Alice', 'Eve']]}")

Series with custom index:
Alice      85
Bob        90
Charlie    78
David      92
Eve        88
dtype: int64

Bob's marks: 90
Alice & Eve:
Alice    85
Eve      88
dtype: int64

In [5]:
# From a dictionary
ages = pd.Series({'Alice': 20, 'Bob': 22, 'Charlie': 21})
print("Series from dictionary:")
print(ages)

Series from dictionary:
Alice      20
Bob        22
Charlie    21
dtype: int64

---

## 3. DataFrame — 2-D Data (Tables)

A **DataFrame** is a table with rows and columns. This is what you'll use 90% of the time!

### 3.1 Creating a DataFrame from a Dictionary (most common)

In [6]:
data = {
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age':     [20, 22, 21, 23, 20],
    'City':    ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai'],
    'Marks':   [85, 90, 78, 92, 88],
    'Grade':   ['A', 'A+', 'B+', 'A+', 'A']
}
df = pd.DataFrame(data)
df

      Name  Age     City  Marks Grade
0    Alice   20    Delhi     85     A
1      Bob   22   Mumbai     90    A+
2  Charlie   21    Delhi     78    B+
3    David   23  Chennai     92    A+
4      Eve   20   Mumbai     88     A

### 3.2 From a list of lists

In [7]:
data = [
    ['Alice', 20, 85],
    ['Bob', 22, 90],
    ['Charlie', 21, 78]
]
df_from_list = pd.DataFrame(data, columns=['Name', 'Age', 'Marks'])
df_from_list

      Name  Age  Marks
0    Alice   20     85
1      Bob   22     90
2  Charlie   21     78

### 3.3 From a NumPy array

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_np = pd.DataFrame(arr, columns=['A', 'B', 'C'])
df_from_np

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

---

## 4. Reading & Writing Data Files

### 4.1 Reading Files

In [9]:
# Examples of reading files (uncomment to use with real files)

# CSV file (most common)
# df = pd.read_csv('students.csv')

# Excel file
# df = pd.read_excel('students.xlsx')

# JSON file
# df = pd.read_json('students.json')

# From a URL
# df = pd.read_csv('https://example.com/data.csv')

# With options
# df = pd.read_csv('students.csv',
#     sep=',',              # delimiter
#     header=0,             # which row has column names
#     index_col='Roll_No',  # use a column as the index
#     usecols=['Name', 'Marks', 'Grade'],  # specific columns only
#     nrows=100,            # first 100 rows only
#     encoding='utf-8'
# )

print("✅ Read functions demonstrated (uncomment with real files)")

✅ Read functions demonstrated (uncomment with real files)

### 4.2 Writing Files

In [10]:
# Examples of writing files (uncomment to use)

# df.to_csv('output.csv', index=False)      # index=False skips row numbers
# df.to_excel('output.xlsx', index=False)
# df.to_json('output.json')

print("✅ Write functions demonstrated (uncomment to save files)")

✅ Write functions demonstrated (uncomment to save files)

---

## 5. Viewing & Inspecting Data

In [11]:
# Create sample data for all examples
data = {
    'Name':   ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Age':    [20, 22, 21, 23, 20, 24, 22],
    'City':   ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi', 'Chennai'],
    'Marks':  [85, 90, 78, 92, 88, 67, 95]
}
df = pd.DataFrame(data)

# First 5 rows
print("=== head() — First 5 rows ===")
print(df.head())

=== head() — First 5 rows ===
      Name  Age     City  Marks
0    Alice   20    Delhi     85
1      Bob   22   Mumbai     90
2  Charlie   21    Delhi     78
3    David   23  Chennai     92
4      Eve   20   Mumbai     88

In [12]:
# Last 3 rows
print("=== tail(3) — Last 3 rows ===")
print(df.tail(3))

=== tail(3) — Last 3 rows ===
    Name  Age     City  Marks
4    Eve   20   Mumbai     88
5  Frank   24    Delhi     67
6  Grace   22  Chennai     95

In [13]:
# Quick overview
print(f"Shape (rows, cols):  {df.shape}")
print(f"Columns:             {list(df.columns)}")
print()
print("=== Data types ===")
print(df.dtypes)

Shape (rows, cols):  (7, 4)
Columns:             ['Name', 'Age', 'City', 'Marks']

=== Data types ===
Name     object
Age       int64
City     object
Marks     int64
dtype: object

In [14]:
# Complete info
print("=== info() ===")
df.info()

=== info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     7 non-null      int64
 2   City    7 non-null      object
 3   Marks   7 non-null      int64
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes

In [15]:
# Statistical summary (numbers only)
print("=== describe() ===")
df.describe()

=== describe() ===

             Age      Marks
count   7.000000   7.000000
mean   21.714286  85.000000
std     1.496026   9.626353
min    20.000000  67.000000
25%    20.500000  81.500000
50%    22.000000  88.000000
75%    22.500000  91.000000
max    24.000000  95.000000

In [16]:
# Unique values and value counts
print(f"Unique values per column:\n{df.nunique()}")
print()
print(f"City value counts:\n{df['City'].value_counts()}")

Unique values per column:
Name     7
Age      5
City     3
Marks    7
dtype: int64

City value counts:
City
Delhi      3
Mumbai     2
Chennai    2
Name: count, dtype: int64

---

## 6. Selecting Data

### 6.1 Select Columns

In [17]:
# Single column (returns Series)
print("=== Single column ===")
print(df['Name'])
print()

# Multiple columns (returns DataFrame)
print("=== Multiple columns ===")
print(df[['Name', 'Marks']])

=== Single column ===
0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
Name: Name, dtype: object

=== Multiple columns ===
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
3    David     92
4      Eve     88
5    Frank     67
6    Grace     95

### 6.2 Select Rows by Position — iloc (integer location)

In [18]:
# First row
print("=== First row (iloc[0]) ===")
print(df.iloc[0])
print()

# Rows 0 to 2
print("=== Rows 0-2 (iloc[0:3]) ===")
print(df.iloc[0:3])
print()

# Specific rows and columns by position
print("=== First 3 rows, first 2 cols (iloc[0:3, 0:2]) ===")
print(df.iloc[0:3, 0:2])

=== First row (iloc[0]) ===
Name     Alice
Age         20
City     Delhi
Marks       85
Name: 0, dtype: object

=== Rows 0-2 (iloc[0:3]) ===
      Name  Age    City  Marks
0    Alice   20   Delhi     85
1      Bob   22  Mumbai     90
2  Charlie   21   Delhi     78

=== First 3 rows, first 2 cols (iloc[0:3, 0:2]) ===
      Name  Age
0    Alice   20
1      Bob   22
2  Charlie   21

### 6.3 Select Rows by Label — loc (label-based)

> 🧠 **iloc vs loc:**
> - `iloc` → **i**nteger position (like array index: 0, 1, 2...)
> - `loc`  → **l**abel-based (uses column names and index labels)

In [19]:
# By index and column name
print(f"df.loc[0, 'Name'] = {df.loc[0, 'Name']}")
print()

# Multiple rows and specific columns
print("=== loc[0:2, ['Name', 'Marks']] ===")
print(df.loc[0:2, ['Name', 'Marks']])

df.loc[0, 'Name'] = Alice

=== loc[0:2, ['Name', 'Marks']] ===
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78

---

## 7. Filtering Data

### 7.1 Basic Filtering

In [20]:
# Students with marks above 85
print("=== Marks > 85 ===")
print(df[df['Marks'] > 85])
print()

# Students from Delhi
print("=== City == Delhi ===")
print(df[df['City'] == 'Delhi'])

=== Marks > 85 ===
    Name  Age     City  Marks
1    Bob   22   Mumbai     90
3  David   23  Chennai     92
4    Eve   20   Mumbai     88
6  Grace   22  Chennai     95

=== City == Delhi ===
      Name  Age   City  Marks
0    Alice   20  Delhi     85
2  Charlie   21  Delhi     78
5    Frank   24  Delhi     67

### 7.2 Multiple Conditions

> ⚠️ **Important:** Use `&` (not `and`) and `|` (not `or`). Always wrap each condition in `()`.

In [21]:
# AND: marks > 85 AND city is Mumbai
print("=== Marks > 85 AND City == Mumbai ===")
print(df[(df['Marks'] > 85) & (df['City'] == 'Mumbai')])
print()

# OR: marks > 90 OR age < 21
print("=== Marks > 90 OR Age < 21 ===")
print(df[(df['Marks'] > 90) | (df['Age'] < 21)])

=== Marks > 85 AND City == Mumbai ===
  Name  Age    City  Marks
1  Bob   22  Mumbai     90
4  Eve   20  Mumbai     88

=== Marks > 90 OR Age < 21 ===
    Name  Age     City  Marks
0  Alice   20    Delhi     85
3  David   23  Chennai     92
4    Eve   20   Mumbai     88
6  Grace   22  Chennai     95

In [22]:
# isin() — check membership
print("=== Age is 20 or 22 ===")
print(df[df['Age'].isin([20, 22])])

=== Age is 20 or 22 ===
    Name  Age     City  Marks
0  Alice   20    Delhi     85
1    Bob   22   Mumbai     90
4    Eve   20   Mumbai     88
6  Grace   22  Chennai     95

In [23]:
# query() — cleaner syntax
print("=== Using query() ===")
print(df.query('Marks > 85 and City == "Mumbai"'))

=== Using query() ===
  Name  Age    City  Marks
1  Bob   22  Mumbai     90
4  Eve   20  Mumbai     88

---

## 8. Adding & Removing Columns/Rows

### 8.1 Adding Columns

In [24]:
# Make a copy to experiment
df2 = df.copy()

# New column with a formula
df2['Percentage'] = df2['Marks']   # Already out of 100

# New column based on condition
df2['Result'] = df2['Marks'].apply(lambda x: 'Pass' if x >= 60 else 'Fail')

# New column with a fixed value
df2['School'] = 'ABC High School'

print(df2)

      Name  Age     City  Marks  Percentage Result           School
0    Alice   20    Delhi     85          85   Pass  ABC High School
1      Bob   22   Mumbai     90          90   Pass  ABC High School
2  Charlie   21    Delhi     78          78   Pass  ABC High School
3    David   23  Chennai     92          92   Pass  ABC High School
4      Eve   20   Mumbai     88          88   Pass  ABC High School
5    Frank   24    Delhi     67          67   Pass  ABC High School
6    Grace   22  Chennai     95          95   Pass  ABC High School

### 8.2 Removing Columns

In [25]:
# Drop one column
df2 = df2.drop('School', axis=1)
print("After dropping 'School':")
print(df2.columns.tolist())

# Drop multiple columns
df2 = df2.drop(['Percentage', 'Result'], axis=1)
print(f"After dropping more: {df2.columns.tolist()}")

After dropping 'School':
['Name', 'Age', 'City', 'Marks', 'Percentage', 'Result']
After dropping more: ['Name', 'Age', 'City', 'Marks']

### 8.3 Adding & Removing Rows

In [26]:
# Add a new row
new_student = pd.DataFrame({'Name': ['Henry'], 'Age': [21], 'City': ['Pune'], 'Marks': [82]})
df3 = pd.concat([df2, new_student], ignore_index=True)
print("After adding Henry:")
print(df3.tail(3))
print()

# Remove row by condition (keep only passing students)
df3_pass = df3[df3['Marks'] >= 70]
print(f"After keeping marks >= 70: {len(df3_pass)} students remain")

After adding Henry:
    Name  Age     City  Marks
5  Frank   24    Delhi     67
6  Grace   22  Chennai     95
7  Henry   21     Pune     82

After keeping marks >= 70: 7 students remain

---

## 9. Handling Missing Data

Missing data is very common in real datasets (empty cells, NaN, null).

In [27]:
# Create sample data with missing values
data_missing = {
    'Name':  ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age':   [20, None, 21, 23, None],
    'Marks': [85, 90, None, 92, 88]
}
df_m = pd.DataFrame(data_missing)
print("Data with missing values (NaN):")
print(df_m)

Data with missing values (NaN):
      Name   Age  Marks
0    Alice  20.0   85.0
1      Bob   NaN   90.0
2  Charlie  21.0    NaN
3    David  23.0   92.0
4      Eve   NaN   88.0

### 9.1 Detecting Missing Values

In [28]:
# Check for missing values
print("=== Missing values (True = NaN) ===")
print(df_m.isnull())
print()

# Count NaN per column
print("=== NaN count per column ===")
print(df_m.isnull().sum())
print()

print(f"Total missing values: {df_m.isnull().sum().sum()}")

=== Missing values (True = NaN) ===
    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

=== NaN count per column ===
Name     0
Age      2
Marks    1
dtype: int64

Total missing values: 3

### 9.2 Handling Missing Values

In [29]:
# Option 1: DROP rows with any missing value
print("=== dropna() — Remove rows with NaN ===")
print(df_m.dropna())
print()

=== dropna() — Remove rows with NaN ===
    Name   Age  Marks
0  Alice  20.0   85.0
3  David  23.0   92.0

In [30]:
# Option 2: FILL missing values with a number
print("=== fillna(0) — Replace NaN with 0 ===")
print(df_m.fillna(0))
print()

=== fillna(0) — Replace NaN with 0 ===
      Name   Age  Marks
0    Alice  20.0   85.0
1      Bob   0.0   90.0
2  Charlie  21.0    0.0
3    David  23.0   92.0
4      Eve   0.0   88.0

In [31]:
# Option 3: FILL with mean (for numeric columns)
df_filled = df_m.copy()
df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].mean())
df_filled['Marks'] = df_filled['Marks'].fillna(df_filled['Marks'].mean())
print("=== fillna(mean) — Replace NaN with column mean ===")
print(df_filled)

=== fillna(mean) — Replace NaN with column mean ===
      Name        Age  Marks
0    Alice  20.000000  85.00
1      Bob  21.333333  90.00
2  Charlie  21.000000  88.75
3    David  23.000000  92.00
4      Eve  21.333333  88.00

---

## 10. Sorting Data

In [32]:
# Sort by Marks (ascending)
print("=== Sorted by Marks (ascending) ===")
print(df.sort_values('Marks'))
print()

# Sort by Marks (descending) — highest first
print("=== Sorted by Marks (descending) ===")
print(df.sort_values('Marks', ascending=False))

=== Sorted by Marks (ascending) ===
      Name  Age     City  Marks
5    Frank   24    Delhi     67
2  Charlie   21    Delhi     78
0    Alice   20    Delhi     85
4      Eve   20   Mumbai     88
1      Bob   22   Mumbai     90
3    David   23  Chennai     92
6    Grace   22  Chennai     95

=== Sorted by Marks (descending) ===
      Name  Age     City  Marks
6    Grace   22  Chennai     95
3    David   23  Chennai     92
1      Bob   22   Mumbai     90
4      Eve   20   Mumbai     88
0    Alice   20    Delhi     85
2  Charlie   21    Delhi     78
5    Frank   24    Delhi     67

In [33]:
# Sort by multiple columns
print("=== Sorted by City (A-Z), then Marks (high-low) ===")
print(df.sort_values(['City', 'Marks'], ascending=[True, False]))

=== Sorted by City (A-Z), then Marks (high-low) ===
      Name  Age     City  Marks
6    Grace   22  Chennai     95
3    David   23  Chennai     92
0    Alice   20    Delhi     85
2  Charlie   21    Delhi     78
5    Frank   24    Delhi     67
1      Bob   22   Mumbai     90
4      Eve   20   Mumbai     88

In [34]:
# Get the rank
df_ranked = df.copy()
df_ranked['Rank'] = df_ranked['Marks'].rank(ascending=False).astype(int)
print("=== With Rank column ===")
print(df_ranked.sort_values('Rank'))

=== With Rank column ===
      Name  Age     City  Marks  Rank
6    Grace   22  Chennai     95     1
3    David   23  Chennai     92     2
1      Bob   22   Mumbai     90     3
4      Eve   20   Mumbai     88     4
0    Alice   20    Delhi     85     5
2  Charlie   21    Delhi     78     6
5    Frank   24    Delhi     67     7

---

## 11. Grouping & Aggregation

GroupBy is one of Pandas' most powerful features — like pivot tables in Excel!

### 11.1 Basic GroupBy

In [35]:
data_gb = {
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'City':    ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Subject': ['Math', 'Math', 'Science', 'Math', 'Science', 'Science'],
    'Marks':   [85, 90, 78, 92, 88, 67]
}
df_gb = pd.DataFrame(data_gb)
print("Data:")
print(df_gb)
print()

# Average marks per city
print("=== Average marks per City ===")
print(df_gb.groupby('City')['Marks'].mean())

Data:
      Name     City  Subject  Marks
0    Alice    Delhi     Math     85
1      Bob   Mumbai     Math     90
2  Charlie    Delhi  Science     78
3    David  Chennai     Math     92
4      Eve   Mumbai  Science     88
5    Frank    Delhi  Science     67

=== Average marks per City ===
City
Chennai    92.000000
Delhi      76.666667
Mumbai     89.000000
Name: Marks, dtype: float64

In [36]:
# Multiple aggregations
print("=== Multiple aggregations per City ===")
print(df_gb.groupby('City')['Marks'].agg(['mean', 'min', 'max', 'count']))

=== Multiple aggregations per City ===
              mean  min  max  count
City
Chennai  92.000000   92   92      1
Delhi    76.666667   67   85      3
Mumbai   89.000000   88   90      2

### 11.2 Group by Multiple Columns

In [37]:
# Average marks per city per subject
print("=== Average marks per City per Subject ===")
print(df_gb.groupby(['City', 'Subject'])['Marks'].mean())

=== Average marks per City per Subject ===
City     Subject
Chennai  Math       92.0
Delhi    Math       85.0
         Science    72.5
Mumbai   Math       90.0
         Science    88.0
Name: Marks, dtype: float64

### 11.3 Named Aggregations (Clean Output)

In [38]:
result = df_gb.groupby('City').agg(
    avg_marks=('Marks', 'mean'),
    top_marks=('Marks', 'max'),
    student_count=('Name', 'count')
).reset_index()

print("=== Named aggregations ===")
print(result)

=== Named aggregations ===
      City  avg_marks  top_marks  student_count
0  Chennai  92.000000         92              1
1    Delhi  76.666667         85              3
2   Mumbai  89.000000         90              2

---

## 12. Merging & Joining DataFrames

Like SQL JOINs — combine tables based on a common column.

### 12.1 Merge (SQL-style Join)

In [39]:
# Student info
students = pd.DataFrame({
    'ID':   [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

# Student marks
marks_df = pd.DataFrame({
    'ID':    [1, 2, 3, 5],
    'Marks': [85, 90, 78, 95]
})

print("Students table:")
print(students)
print()
print("Marks table:")
print(marks_df)

Students table:
   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

Marks table:
   ID  Marks
0   1     85
1   2     90
2   3     78
3   5     95

In [40]:
# Inner join (only matching IDs)
print("=== INNER join ===")
print(pd.merge(students, marks_df, on='ID', how='inner'))
print()

# Left join (all students, marks if available)
print("=== LEFT join ===")
print(pd.merge(students, marks_df, on='ID', how='left'))
print()

# Outer join (all from both)
print("=== OUTER join ===")
print(pd.merge(students, marks_df, on='ID', how='outer'))

=== INNER join ===
   ID     Name  Marks
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     78

=== LEFT join ===
   ID     Name  Marks
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie   78.0
3   4    David    NaN

=== OUTER join ===
   ID     Name  Marks
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie   78.0
3   4    David    NaN
4   5      NaN   95.0

### 12.2 Concat (Stack DataFrames)

In [41]:
# Stack vertically (add more rows)
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Marks': [85, 90]})
df2 = pd.DataFrame({'Name': ['Charlie', 'David'], 'Marks': [78, 92]})

combined = pd.concat([df1, df2], ignore_index=True)
print("=== Vertical concat ===")
print(combined)

=== Vertical concat ===
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
3    David     92

---

## 13. String Operations

Pandas has built-in string methods through `.str` accessor!

In [42]:
df_str = pd.DataFrame({
    'Name':  ['alice smith', 'BOB JONES', 'Charlie Brown', '  david  '],
    'Email': ['alice@gmail.com', 'bob@yahoo.com', 'charlie@gmail.com', 'david@outlook.com']
})

# Case conversion
print("=== upper() ===")
print(df_str['Name'].str.upper())
print()

print("=== title() ===")
print(df_str['Name'].str.title())
print()

print("=== strip() ===")
print(df_str['Name'].str.strip())

=== upper() ===
0      ALICE SMITH
1        BOB JONES
2    CHARLIE BROWN
3          DAVID
Name: Name, dtype: object

=== title() ===
0      Alice Smith
1        Bob Jones
2    Charlie Brown
3          David
Name: Name, dtype: object

=== strip() ===
0      alice smith
1        BOB JONES
2    Charlie Brown
3            david
Name: Name, dtype: object

In [43]:
# Contains (search within strings)
print("=== Email contains 'gmail' ===")
print(df_str['Email'].str.contains('gmail'))
print()

# Extract domain from email
df_str['Domain'] = df_str['Email'].str.split('@').str[1]
print("=== Extracted domains ===")
print(df_str[['Email', 'Domain']])

=== Email contains 'gmail' ===
0     True
1    False
2     True
3    False
Name: Email, dtype: bool

=== Extracted domains ===
               Email       Domain
0    alice@gmail.com    gmail.com
1      bob@yahoo.com    yahoo.com
2  charlie@gmail.com    gmail.com
3  david@outlook.com  outlook.com

---

## 14. Apply & Lambda Functions

Apply lets you run **any function** on your data — ultimate flexibility!

### 14.1 Apply with a Named Function

In [44]:
df_apply = pd.DataFrame({
    'Name':  ['Alice', 'Bob', 'Charlie'],
    'Marks': [85, 45, 78]
})

def get_grade(marks):
    if marks >= 90: return 'A+'
    elif marks >= 80: return 'A'
    elif marks >= 70: return 'B'
    elif marks >= 60: return 'C'
    else: return 'F'

df_apply['Grade'] = df_apply['Marks'].apply(get_grade)
print(df_apply)

      Name  Marks Grade
0    Alice     85     A
1      Bob     45     F
2  Charlie     78     B

### 14.2 Lambda Functions (quick one-liners)

In [45]:
# Double the marks
df_apply['Double'] = df_apply['Marks'].apply(lambda x: x * 2)

# Pass/Fail
df_apply['Result'] = df_apply['Marks'].apply(lambda x: 'Pass' if x >= 50 else 'Fail')

# Apply to entire DataFrame (row-wise)
df_apply['Summary'] = df_apply.apply(
    lambda row: f"{row['Name']} scored {row['Marks']}", axis=1
)
print(df_apply)

      Name  Marks Grade  Double Result            Summary
0    Alice     85     A     170   Pass    Alice scored 85
1      Bob     45     F      90   Fail      Bob scored 45
2  Charlie     78     B     156   Pass  Charlie scored 78

### 14.3 Map (for simple value replacement)

In [46]:
# Replace values using a dictionary
grade_map = {'A+': 10, 'A': 9, 'B': 8, 'C': 7, 'F': 0}
df_apply['Grade_Points'] = df_apply['Grade'].map(grade_map)
print(df_apply[['Name', 'Grade', 'Grade_Points']])

      Name Grade  Grade_Points
0    Alice     A             9
1      Bob     F             0
2  Charlie     B             8

---

## 15. Pivot Tables

Like Excel pivot tables — summarize data in a cross-tabulation format.

In [47]:
data_pivot = {
    'Student': ['Alice', 'Alice', 'Bob', 'Bob', 'Charlie', 'Charlie'],
    'Subject': ['Math', 'Science', 'Math', 'Science', 'Math', 'Science'],
    'Marks':   [85, 90, 78, 82, 92, 88]
}
df_pivot = pd.DataFrame(data_pivot)
print("Original data:")
print(df_pivot)
print()

# Pivot table
pivot = df_pivot.pivot_table(
    values='Marks',       # What to aggregate
    index='Student',      # Rows
    columns='Subject',    # Columns
    aggfunc='mean'        # Aggregation function
)
print("Pivot table:")
print(pivot)

Original data:
   Student  Subject  Marks
0    Alice     Math     85
1    Alice  Science     90
2      Bob     Math     78
3      Bob  Science     82
4  Charlie     Math     92
5  Charlie  Science     88

Pivot table:
Subject  Math  Science
Student
Alice    85.0     90.0
Bob      78.0     82.0
Charlie  92.0     88.0

---

## 16. Date & Time

In [48]:
# Create date column
df_date = pd.DataFrame({
    'Date': ['2024-01-15', '2024-02-20', '2024-03-25', '2024-04-10'],
    'Sales': [150, 200, 180, 220]
})

# Convert string to datetime
df_date['Date'] = pd.to_datetime(df_date['Date'])

# Extract parts
df_date['Year'] = df_date['Date'].dt.year
df_date['Month'] = df_date['Date'].dt.month
df_date['Day'] = df_date['Date'].dt.day
df_date['Day_Name'] = df_date['Date'].dt.day_name()
df_date['Quarter'] = df_date['Date'].dt.quarter

print(df_date)

        Date  Sales  Year  Month  Day   Day_Name  Quarter
0 2024-01-15    150  2024      1   15     Monday        1
1 2024-02-20    200  2024      2   20    Tuesday        1
2 2024-03-25    180  2024      3   25     Monday        1
3 2024-04-10    220  2024      4   10  Wednesday        2

In [49]:
# Filter by date range
mask = (df_date['Date'] >= '2024-02-01') & (df_date['Date'] <= '2024-03-31')
print("=== Feb to March data ===")
print(df_date[mask])

=== Feb to March data ===
        Date  Sales  Year  Month  Day Day_Name  Quarter
1 2024-02-20    200  2024      2   20  Tuesday        1
2 2024-03-25    180  2024      3   25   Monday        1

---

## 17. 🎯 Real-World Mini Project: Student Report Card

In [50]:
import pandas as pd

# Student data
data = {
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Math':    [85, 90, 78, 45, 92],
    'Science': [90, 88, 72, 55, 95],
    'English': [78, 95, 80, 60, 88],
    'History': [88, 82, 76, 40, 91]
}
df_report = pd.DataFrame(data)

# Calculate total and average
subjects = ['Math', 'Science', 'English', 'History']
df_report['Total'] = df_report[subjects].sum(axis=1)
df_report['Average'] = df_report[subjects].mean(axis=1).round(2)

# Assign grades
def assign_grade(avg):
    if avg >= 90: return 'A+'
    elif avg >= 80: return 'A'
    elif avg >= 70: return 'B'
    elif avg >= 60: return 'C'
    else: return 'F'

df_report['Grade'] = df_report['Average'].apply(assign_grade)

# Assign rank
df_report['Rank'] = df_report['Average'].rank(ascending=False).astype(int)

# Sort by rank
df_report = df_report.sort_values('Rank')

print("📋 STUDENT REPORT CARD")
print("=" * 70)
print(df_report.to_string(index=False))
print("=" * 70)
print(f"\n🏆 Topper: {df_report.iloc[0]['Name']} with {df_report.iloc[0]['Average']}% average!")

📋 STUDENT REPORT CARD
======================================================================
   Name  Math  Science  English  History  Total  Average Grade  Rank
    Eve    92       95       88       91    366    91.50    A+     1
    Bob    90       88       95       82    355    88.75     A     2
  Alice    85       90       78       88    341    85.25     A     3
Charlie    78       72       80       76    306    76.50     B     4
  David    45       55       60       40    200    50.00     F     5
======================================================================

🏆 Topper: Eve with 91.5% average!

## 18. 🎯 Mini Project 2: Sales Data Analysis

In [51]:
import pandas as pd
import numpy as np

# Create sample sales data
np.random.seed(42)
dates = pd.date_range('2024-01-01', periods=100, freq='D')
data_sales = {
    'Date': dates,
    'Product': np.random.choice(['Laptop', 'Phone', 'Tablet', 'Headphones'], 100),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], 100),
    'Units': np.random.randint(1, 20, 100),
    'Price': np.random.choice([999, 699, 499, 149], 100)
}
df_sales = pd.DataFrame(data_sales)
df_sales['Revenue'] = df_sales['Units'] * df_sales['Price']

print("Sample data:")
print(df_sales.head())
print(f"\nTotal rows: {len(df_sales)}")

Sample data:
        Date     Product Region  Units  Price  Revenue
0 2024-01-01      Tablet   East      7    499     3493
1 2024-01-02  Headphones  South     17    149     2533
2 2024-01-03      Laptop  South      4    149      596
3 2024-01-04      Tablet   West      5    499     2495
4 2024-01-05      Tablet  South      7    149     1043

Total rows: 100

In [52]:
# Revenue by Product
print("📊 Revenue by Product:")
print(df_sales.groupby('Product')['Revenue'].sum().sort_values(ascending=False))
print()

# Revenue by Region
print("📊 Revenue by Region:")
print(df_sales.groupby('Region')['Revenue'].sum().sort_values(ascending=False))

📊 Revenue by Product:
Product
Laptop        124763
Phone         123534
Headphones    111764
Tablet         91192
Name: Revenue, dtype: int64

📊 Revenue by Region:
Region
East     152920
North    132039
West      90331
South     75963
Name: Revenue, dtype: int64

---

## 📝 Quick Cheat Sheet

```
CREATION:
  pd.Series([1,2,3])                → 1-D data
  pd.DataFrame({'col': [1,2,3]})    → 2-D table
  pd.read_csv('file.csv')           → from CSV

INSPECTION:
  df.head()  df.tail()  df.shape  df.info()  df.describe()

SELECTION:
  df['col']           → single column
  df.iloc[0]          → by position
  df.loc[0, 'col']    → by label

FILTERING:
  df[df['col'] > 5]                     → condition
  df[(df['A'] > 5) & (df['B'] < 10)]   → multiple

MISSING DATA:
  df.isnull().sum()  df.dropna()  df.fillna(value)

GROUPING:
  df.groupby('col').mean()
  df.groupby('col').agg(['mean','sum'])

MERGING:
  pd.merge(df1, df2, on='key')  pd.concat([df1, df2])
```

---

> 🎉 **Congratulations!** You now know Pandas!  
> **Next up:** Learn **Matplotlib** for creating beautiful visualizations!